### ISSUE TITLE
Running RDFS forward chaining generates triples with literals on subject position

### ISSUE THREAD

**Issue by patrickwestphal** [SANSA-Stack/SANSA-Inference#1]
I ran the RDFS forward chaining (on GO) through the example set up in [SANSA-Examples/sansa-examples-spark](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/sansa-examples-spark/src/main/scala/net/sansa_stack/examples/spark/inference/RDFGraphInference.scala) and got triples looking like this
```
<"Reactome:REACT_90070"^^<http://www.w3.org/2001/XMLSchema#string>> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Resource> .
```
in the output.
I think a literal check is needed here: https://github.com/SANSA-Stack/SANSA-Inference/blob/develop/sansa-inference-spark/src/main/scala/net/sansa_stack/inference/spark/forwardchaining/ForwardRuleReasonerRDFS.scala#L186

**Comment by LorenzBuehmann** [comment]
Oh yes, you're right. I didn't check this. Unfortunately, the rule in [RDFS 1.1 Semantics](https://www.w3.org/TR/rdf11-mt/) is just defined as follows:

|        | If S contains: | then S RDFS entails recognizing D: |
|--------|----------------|------------------------------------|
| rdfs4b | xxx aaa yyy.   | yyy rdf:type rdfs:Resource .       |

and there is no distinction of `yyy`. 

We also have to keep in mind, that rules `rdfs1` and `rdfs13` are still missing, as I didn't know whether those really need to be implemented.
