### ISSUE TITLE
Running axioms forward chaining generates different result set from triples inference.

### ISSUE THREAD

**Issue by GezimSejdiu** [SANSA-Stack/SANSA-Inference#10]
While creating the [axioms inference example](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/sansa-examples-spark/src/main/scala/net/sansa_stack/examples/spark/inference/axioms/RDFGraphInference.scala) I noticed that the result set is different from the one implemented on [triples inference example](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/sansa-examples-spark/src/main/scala/net/sansa_stack/examples/spark/inference/triples/RDFGraphInference.scala). 
Instead of returning inferred graph, it just returns the inferred axioms. Is there a reason behind it? Shall we consider being consistent in both cases?

Best regards,

**Comment by Hebaallahibrahim** [comment]
Hi Gezim, thanks for your notice. I changed it to return the inferred Graph.

**Comment by Hebaallahibrahim** [comment]
Hi @GezimSejdiu, Can we merge the PR updates and close this issue?

**Comment by GezimSejdiu** [comment]
Hi @Hebaallahibrahim ,
PR #11 needs at least one approve from the assigned reviewers. In this case, @patrickwestphal is the reviewer. Let's wait from him and then when the PR is approved we can close the issue.

Best,

**Comment by GezimSejdiu** [comment]
Resolved via #11
